### ISSUE TITLE
Get George ready to go at DWR

### ISSUE THREAD

**Issue by qjhart** [CSTARS/spatial-cimis#14]
In order to be able to do work on the SpatialCIMIS servers, we need to get George setup.  The following requirements are needed: 

- [x] George - add putty and pageant to your admin console.
- [x] Mike - verify that's still okay w/ DWR
- [x] George - create a key pair on your admin console and send to Mike
- [x] Mike - create user for george on Production: rec, arc, pro.  On the testing machine, and on the new production machine. 
- [x] Mike - Also add George's key to the cimis user on those machines
- [x] Mike - Sudo access for george on above machines

**Comment by qjhart** [comment]
@gjscheer-ucd now that you have your account, please follow through w/ this request.  You should have all the IPs you need, including the receiver.  When this is complete we can do another video.

**Comment by gjscheer-ucd** [comment]
@qjhart I've put in a request to Mike Clark and you for ssh access to the DWR and UCD servers with my public key.

**Comment by gjscheer-ucd** [comment]
@qjhart I need ssh access to goes-w.casil.ucdavis.edu.  Please create a account gjscheer with sudo access using my public key https://ucdavis.app.box.com/v/gjscheer-keys

**Comment by gjscheer-ucd** [comment]
- [ ]
