### ISSUE TITLE
Post video of the GOES operation

### ISSUE THREAD

**Issue by qjhart** [CSTARS/spatial-cimis#15]
George and I will host a zoom video session where I briefly go over the operation of the Spatial CIMIS setup.  And get his questions.  We will post this video for later review.

**Comment by gjscheer-ucd** [comment]
[Video of spatial CIMIS theory of operation with GRASS operations](https://ucdavis.box.com/s/zm7d9463t9zyjuq9p94a3nlzv56rgmvx)
