### ISSUE TITLE
grass-addons compiling issue

### ISSUE THREAD

**Issue by gjscheer-ucd** [CSTARS/spatial-cimis#20]
First attempt at compiling addons requires `grass/gis.h` but I'm not sure how to include it?  Try appending /usr/local/grass70/include to $GHLIB but that breaks. 

`make GRASS_HOME=. MODULE_TOPDIR=${GH} DISTDIR=${GRASS_ADDON} ARCH_DISTDIR=${GRASS_ADDON} ARCH_INC=-I${GH}/include ARCH_LIBDIR=${GHLIB} cmd
c++ -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -I/home/gjscheer/grass/include -I/home/gjscheer/grass/include    -DPACKAGE=\""grassmods"\"  -I/usr/local/include/libgvar -I/home/gjscheer/grass/include -I/home/gjscheer/grass/include -DRELDIR=\"/home/gjscheer/src/qjhart.grass-addons/r.in.gvar\" -o OBJ.x86_64-pc-linux-gnu/grasswriterLib.o -c grasswriterLib.cpp
grasswriterLib.cpp:28:23: fatal error: grass/gis.h: No such file or directory
compilation terminated.
/usr/lib/grass70/include/Make/Compile.make:35: recipe for target 'OBJ.x86_64-pc-linux-gnu/grasswriterLib.o' failed
make: *** [OBJ.x86_64-pc-linux-gnu/grasswriterLib.o] Error 1`

**Comment by qjhart** [comment]
Updated r.solpos to use standard g.extension for building.
