### ISSUE TITLE
Compile perl modules geo::proj4 for RedHat

### ISSUE THREAD

**Issue by gjscheer-ucd** [CSTARS/spatial-cimis#88]
If the package **perl-Geo-Proj4** cannot be found or created from [issue 71](https://github.com/CSTARS/spatial-cimis/issues/71) then the perl modules for Geo::Proj4 will have to be manually compiled for Red Hat.

https://metacpan.org/pod/distribution/Geo-Proj4/lib/Geo/Proj4.pod
https://rt.cpan.org/Public/Bug/Display.html?id=106410

**Comment by qjhart** [comment]
I removed the part about Quinn has some notes on compiling Geo::Proj4, that is no longer required for GOES-17 data.

**Comment by qjhart** [comment]
I think all you need to do is: `sudo cpan install Geo::Proj4`

**Comment by qjhart** [comment]
I have verified that Geo::Proj4 seems to install okay on testing.  This is what you should be able to do to complete  this installation: 
1. Download the Geo::Proj4 package from https://metacpan.org/pod/distribution/Geo-Proj4/lib/Geo/Proj4.pod onto your windows machine
2. Use filezilla or equiv to push to testing machine
(Or you can get from `file://dev/~qhart/ Geo-Proj4-1.09.tar.gz`
3. `tar -xzf  Geo-Proj4-1.09.tar.gz`
4. cd  Geo-Proj4-1.09
5. make test
6 sudo make install 

This will install the files to the /usr/local/lib.  I've done all the steps but the install step.
